# Set minimum and maximum cohort size parameters.
min_cohort_size: 20  # TODO Could we live with 15 here?
max_cohort_size: 50  # TODO Maybe increase this for production?

# Select the sample sets to include in the build.
sample_sets:
    # - "3.0"
    # smaller dataset for development
    - "AG1000G-ML-A"
    - "AG1000G-BF-A"
    
# Select the contigs to analyse.
contigs:
    - "2RL"
    # - "3RL"
    # - "X"
    
# Pin the cohorts analysis version in order to get reproducible
# builds.
cohorts_analysis: "20230223"

# Select the contig to use for H12 window size calibration.
h12_calibration_contig: "3L"

# Set this value to False when running on datalab, because it's 
# better to read data directly from GCS.
use_gcs_cache: False

# Set this value to "single-threaded" when running snakemake with
# more than 1 CPU to avoid thrashing. Otherwise, both dask and
# snakemake will be trying to use multiple CPUs, and so CPU 
# resources are likely to be oversubscribed.
dask_scheduler: "single-threaded"
