min_cohort_size: 20
max_cohort_size: 50  # TODO maybe increase this for production
ag:
  sample_sets:
    - "AG1000G-BF-A"
  contigs:
    # TODO use joined arms when we can
    - "2R"
    - "3R"
    - "X"
  h12_calibration_contig: "3L"
