name: selection-atlas-requirements
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.12
    - numpy
    - snakemake
    - papermill
    - scipy
    - pandas
    - dask
    - numba
    - matplotlib
    - fsspec
    - gcsfs
    - jupyterlab
    - jupyter-book
    - BioPython
    - google-cloud-sdk
    - scikit-allel
    - bokeh
    - statsmodels
    - ipyleaflet
    - tqdm
    - ipywidgets
    - plotly
    - xarray
    - lmfit
    - zarr
    - pyprojroot
    - geopandas
    - iso3166
    - pytorch-cpu
    - nomkl
    - pre-commit
    - ruff
    - snakefmt
    - pip
    - pip:
          - jsonschema>=3.1.0
          - malariagen_data
