name: selection-atlas-requirements
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.11
    - numpy
    - snakemake
    - papermill
    - scipy
    - pandas
    - dask
    - numba
    - matplotlib
    - fsspec
    - gcsfs
    - jupyterlab
    - jupyter-book==0.15.1
    - BioPython
    - gsutil
    - scikit-allel
    - bokeh>=3.1
    - statsmodels
    - ipyleaflet
    - tqdm
    - ipywidgets
    - plotly
    - xarray
    - lmfit
    - zarr
    - pyprojroot
    - geopandas
    - iso3166
    - pip
    - pip:
          - jsonschema>=3.1.0
          - malariagen_data>=7.10.0
