name: selection-atlas-requirements
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.10
    - numpy<1.24
    - snakemake
    - papermill
    - scipy
    - pandas
    - dask
    - numba
    - matplotlib
    - fsspec
    - gcsfs
    - jupyterlab
    - jupyter-book==0.15.1
    - BioPython
    - gsutil
    - scikit-allel
    - bokeh<3.0
    - statsmodels
    - ipyleaflet
    - tqdm
    - ipywidgets
    - plotly
    - xarray
    - lmfit
    - zarr
    - pyprojroot
    - geopandas
    - iso3166
    - pip
    - pip:
          - jsonschema>=3.1.0
          - numpydoc==1.2.0
          - malariagen_data>=7.1.1
