name: deploy-site

on:
  push:
    branches:
      - master


jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install conda environment
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: workflow/common/envs/selection-atlas.yamlas.yaml
          environment-name: selection-atlas
          cache-downloads: true

      # set up google cloud
      - id: auth
        name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 363.0.0"

      - name: Check gcloud CLI
        run: gcloud info

      # - name: Download results from GCS
      #   run: |
      #       mkdir -pv results/{analysis_version}/gwss
      #       gcloud storage rsync -r gs://vo_selection_atlas_dev_us_central1/results/{analysis_version}/gwss/ results/{analysis_version}/gwss/
      #       find results -type f -exec touch {} +

      # - name: Run site workflow
      #   uses: snakemake/snakemake-github-action@v1
      #   with:
      #     directory: '.'
      #     snakefile: 'workflow/site.smk'
      #     args: '--cores 1 --conda-cleanup-pkgs cache'
      #     show-disk-usage-on-error: true

      # TODO fix this to the right directory path.
      # # Push the book's HTML to github-pages
      # - name: GitHub Pages action
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: results/{analysis_version}/site/docs/_build/html
