name: selection-atlas

on: pull_request

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: selection-atlas
        
      - name: Activate micromamba
        run: eval "$(micromamba shell hook --shell=bash)"
      - name: Activate mamba environment
        run: micromamba activate selection-atlas

      - name: Test workflow 
        run: snakemake --cores 1 --use-conda --configfile .test/config.yaml