name: selection-atlas

on: pull_request

jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test workflow paired-end
        uses: snakemake/snakemake-github-action@v1.23.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          stagein: 'pip install geopandas'
          args: '--cores 4 --use-conda --configfile .test/config/config_paired_end.yaml --conda-cleanup-pkgs cache'
